#!/usr/bin/env bash
command -v foo >/dev/null 2>&1 || { echo >&2 "requires GNU parallel"; exit 1; }

function ask(){
	echo
	[[ "$2" ]] && echo "$2"
	text="$1"
	read -p "$text [Yn] " DOIT
	[[ "${DOIT:0:1}" == 'n' || "${DOIT:0:1}" == 'N' ]] && echo 'abort...' && exit 1
}

echo
ask "deploy $(ah env)?"
ah status | grep $(ah env) | cut -f6 | parallel ssh {} sudo ah-client deploy
